<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="Here we provide a detailed analysis using more sophisticated statistics techniques.">

<title>Analysis – MA [46]15 Final Project Team 7</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">MA [46]15 Final Project Team 7</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./big_picture.html"> 
<span class="menu-text">Where You Live, What You Look Like, and Whether You’re Insured Might Just Predict Your Health</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./analysis.html" aria-current="page"> 
<span class="menu-text">Analysis</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./data.html"> 
<span class="menu-text">Data</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#motivation-and-research-questions" id="toc-motivation-and-research-questions" class="nav-link active" data-scroll-target="#motivation-and-research-questions">Motivation and Research Questions</a>
  <ul class="collapse">
  <li><a href="#motivation" id="toc-motivation" class="nav-link" data-scroll-target="#motivation">Motivation</a></li>
  <li><a href="#research-questions" id="toc-research-questions" class="nav-link" data-scroll-target="#research-questions">Research Questions</a></li>
  </ul></li>
  <li><a href="#statistical-analysis" id="toc-statistical-analysis" class="nav-link" data-scroll-target="#statistical-analysis">Statistical Analysis</a></li>
  <li><a href="#modeling-and-inference" id="toc-modeling-and-inference" class="nav-link" data-scroll-target="#modeling-and-inference">Modeling and Inference</a>
  <ul class="collapse">
  <li><a href="#key-findings-from-model-output" id="toc-key-findings-from-model-output" class="nav-link" data-scroll-target="#key-findings-from-model-output">Key Findings From Model Output</a></li>
  <li><a href="#cross-validation-results" id="toc-cross-validation-results" class="nav-link" data-scroll-target="#cross-validation-results">Cross-Validation Results</a></li>
  <li><a href="#residual-analysis-and-model-assumptions" id="toc-residual-analysis-and-model-assumptions" class="nav-link" data-scroll-target="#residual-analysis-and-model-assumptions">Residual Analysis and Model Assumptions</a></li>
  </ul></li>
  <li><a href="#flaws-and-limitations-in-analysis" id="toc-flaws-and-limitations-in-analysis" class="nav-link" data-scroll-target="#flaws-and-limitations-in-analysis">Flaws and limitations in analysis</a></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions">Conclusions</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis</h1>
</div>

<div>
  <div class="description">
    Here we provide a detailed analysis using more sophisticated statistics techniques.
  </div>
</div>


<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p><img src="images/analysis_pic.jpg" class="img-fluid"></p>
<section id="motivation-and-research-questions" class="level1">
<h1>Motivation and Research Questions</h1>
<section id="motivation" class="level2">
<h2 class="anchored" data-anchor-id="motivation">Motivation</h2>
<p>The main purpose of this study is to investigate the disparities in chronic disease prevalence across different racial and ethnic groups in the United States. This project also seeks to examine the relationship between preventive health measures—such as vaccination rates and cancer screenings—and chronic disease outcomes, with a focus on potential gaps in access and utilization. By incorporating data on income levels and insurance coverage, the analysis aims to uncover how socioeconomic factors contribute to these health disparities. Understanding these relationships can help identify the most influential factors affecting chronic disease prevalence and support efforts to improve health equity and outcomes nationwide.</p>
</section>
<section id="research-questions" class="level2">
<h2 class="anchored" data-anchor-id="research-questions">Research Questions</h2>
<ol type="1">
<li><p>How does chronic disease prevalence vary among different racial and ethnic groups across U.S. states?</p></li>
<li><p>What are the patterns of preventive health measure usage (e.g., screenings, vaccinations) among racial and ethnic groups, and how do these relate to disease outcomes?</p></li>
<li><p>How do uninsurance rates vary across racial and income groups?</p></li>
<li><p>Do income level and uninsurance rates correlate with chronic disease prevalence and preventive health measure usage?</p></li>
</ol>
</section>
</section>
<section id="statistical-analysis" class="level1">
<h1>Statistical Analysis</h1>
<p>To begin addressing our first research question, we created a bar plot visualizing the average crude prevalence of several chronic health conditions by race and ethnicity. We decided to investigate health disparities across racial and ethnic groups by examining the prevalence of seven specific health outcomes: <u>Alcohol use</u>, <u>Arthritis</u>, <u>Asthma</u>, <u>COPD (Chronic Obstructive Pulmonary Disease)</u>, <u>Diabetes</u>, <u>Disability</u>, and <u>Mental Health issues</u>. Each condition was averaged within each racial or ethnic category to allow for clearer comparisons across groups.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The bar chart shown above highlights distinct disparities in chronic disease prevalence. Notably, Multiracial and American Indian/Alaska Native populations consistently exhibit higher rates across multiple conditions, with especially elevated levels for Disability and Arthritis concerns. In contrast, Asian populations generally report lower average prevalence across all conditions analyzed. These patterns suggest that chronic disease burdens are not distributed equally and may reflect underlying structural inequities in healthcare access, environmental exposures, or social determinants of health.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We then decided to investigate if sex might be another critical dimension in understanding patterns of chronic disease. Biological differences, social roles, and health behaviors can all contribute to divergent health outcomes between men and women. To explore these potential disparities, we constructed a bar plot comparing average prevalence rates for the same set of chronic health conditions.</p>
<p>The resulting visualization reveals clear differences in chronic disease prevalence between males and females. Arthritis and Disability remain the most prevalent conditions overall, consistent with our earlier findings. However, the distribution of these conditions varies by sex. Alcohol use and Diabetes show higher average prevalence among men, whereas women experience higher rates of Arthritis, Asthma, COPD, Disability, and Mental Health issues. These findings highlight that sex-based health disparities are condition-specific and may reflect differing biological susceptibilities, healthcare-seeking behaviors, or exposures to risk factors.</p>
<p>These initial visualizations provides a compelling entry point into our analysis. It not only supports the presence of disparities in chronic disease prevalence, but also sets the stage for more detailed investigation into the socioeconomic and preventive care factors that may be contributing to these outcomes.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To explore our second research question—<em>What are the patterns of preventive health measure usage among racial and ethnic groups, and how do these relate to disease outcomes?</em>—we visualized the average percentage of adults engaging in four key preventive health behaviors, broken down by race and ethnicity. The graph above illustrates trends across the following categories:</p>
<ul>
<li><p>Colorectal cancer screening among adults aged 45–75 years</p></li>
<li><p>Influenza vaccination among adults</p></li>
<li><p>Counseling for physical activity among adults with arthritis</p></li>
<li><p>Routine checkup within the past year among adults</p></li>
</ul>
<p>This visualization highlights several important patterns. First, routine checkups maintain relatively high participation across all racial groups, with especially high rates among Black and Multiracial populations. However, when it comes to influenza vaccination, participation is markedly lower overall, with Black, Hispanic, and American Indian/Alaska Native populations showing the lowest averages—suggesting potential barriers to access or vaccine hesitancy in these communities.</p>
<p>The colorectal cancer screening and physical activity counseling among adults with arthritis show a more uneven distribution. The Asian and White populations tend to have higher rates of colorectal screening, while Multiracial and American Indian/Alaska Native groups show moderately lower usage. Counseling for physical activity shows notable dips for Hawaiian/Pacific Islander and Multiracial populations, which may point to inconsistencies in healthcare provider practices or systemic disparities in arthritis care.</p>
<p>Taken together, these disparities in preventive measure usage may help explain some of the patterns seen in chronic disease prevalence. For instance, groups with consistently lower rates of screenings and vaccinations—such as American Indian/Alaska Native and Multiracial populations—also showed higher rates of chronic conditions in our earlier analysis. This reinforces the idea that inequities in preventive care access may contribute to unequal health outcomes.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Building on the patterns observed in preventive care usage, we turned to a critical question: Why do certain racial and ethnic groups consistently experience lower access to preventive treatment? One major hypothesis centers on the role of socioeconomic factors, particularly insurance coverage, as a gateway to regular and proactive healthcare. To investigate this, we visualized insurance coverage rates across racial and ethnic groups, broken down by income level. The graph shows a clear, expected trend: as income level increases—from below 135% of the federal poverty line to the general population—insurance coverage increases across all racial and ethnic groups. This upward trend confirms the strong, positive correlation between income and access to insurance, reinforcing the idea that economic stability plays a critical role in healthcare access.</p>
<p>However, the graph also reveals persistent structural inequities. Even when controlling for income level, Hispanic and American Indian/Alaska Native groups show consistently lower coverage rates compared to other populations. This suggests that raising income alone does not eliminate racial disparities in health coverage. These inequities may be driven by additional barriers such as language access, documentation status, discrimination in insurance systems, or geographic inaccessibility to employer-based plans or Medicaid expansion.</p>
<p>In contrast, Asian and White populations consistently exhibit the highest rates of insurance coverage, often exceeding 90% even at moderate income levels. This may reflect higher rates of employment in sectors that offer employer-sponsored insurance, better navigation of eligibility and enrollment processes, or other structural advantages that facilitate consistent access.</p>
</section>
<section id="modeling-and-inference" class="level1">
<h1>Modeling and Inference</h1>
<p>To formally assess the relationships between disease prevalence and socioeconomic factors, we implemented a Multiple Linear Regression model using DataValue (representing disease prevalence) as the response variable. Our predictor variables included Race, Sex, Income, and PCTIC (percent insured), each selected based on our earlier exploratory analysis.</p>
<p>We considered multiple transformations and groupings. Race and income were treated as categorical variables to reflect policy-relevant groupings, while PCTIC was kept numeric to reflect its continuous nature. We did not include interaction terms in this version of the model but recognize that interactions (e.g., Race × Income or Race × PCTIC) could be explored in future work to capture more nuanced disparities.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Multiple Linear Regression Results</caption>
<thead>
<tr class="header">
<th style="text-align: left;">term</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">std.error</th>
<th style="text-align: right;">statistic</th>
<th style="text-align: left;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">20.171007</td>
<td style="text-align: right;">0.196574</td>
<td style="text-align: right;">102.612841</td>
<td style="text-align: left;">&lt;0.000001</td>
</tr>
<tr class="even">
<td style="text-align: left;">RaceASN</td>
<td style="text-align: right;">-13.984137</td>
<td style="text-align: right;">0.077820</td>
<td style="text-align: right;">-179.699338</td>
<td style="text-align: left;">&lt;0.000001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RaceBLK</td>
<td style="text-align: right;">-7.601250</td>
<td style="text-align: right;">0.066610</td>
<td style="text-align: right;">-114.115848</td>
<td style="text-align: left;">&lt;0.000001</td>
</tr>
<tr class="even">
<td style="text-align: left;">RaceHAPI</td>
<td style="text-align: right;">-5.803573</td>
<td style="text-align: right;">0.164818</td>
<td style="text-align: right;">-35.211950</td>
<td style="text-align: left;">&lt;0.000001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RaceHIS</td>
<td style="text-align: right;">-6.925467</td>
<td style="text-align: right;">0.060358</td>
<td style="text-align: right;">-114.739359</td>
<td style="text-align: left;">&lt;0.000001</td>
</tr>
<tr class="even">
<td style="text-align: left;">RaceMRC</td>
<td style="text-align: right;">-0.768362</td>
<td style="text-align: right;">0.066162</td>
<td style="text-align: right;">-11.613398</td>
<td style="text-align: left;">&lt;0.000001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">RaceWHT</td>
<td style="text-align: right;">-7.588757</td>
<td style="text-align: right;">0.065138</td>
<td style="text-align: right;">-116.503574</td>
<td style="text-align: left;">&lt;0.000001</td>
</tr>
<tr class="even">
<td style="text-align: left;">SexFemale</td>
<td style="text-align: right;">-0.090256</td>
<td style="text-align: right;">0.039583</td>
<td style="text-align: right;">-2.280195</td>
<td style="text-align: left;">0.022597</td>
</tr>
<tr class="odd">
<td style="text-align: left;">SexMale</td>
<td style="text-align: right;">0.099538</td>
<td style="text-align: right;">0.039652</td>
<td style="text-align: right;">2.510257</td>
<td style="text-align: left;">0.012065</td>
</tr>
<tr class="even">
<td style="text-align: left;">Income&lt; 200% poverty</td>
<td style="text-align: right;">-0.022737</td>
<td style="text-align: right;">0.055534</td>
<td style="text-align: right;">-0.409430</td>
<td style="text-align: left;">0.682224</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Income&lt; 250% poverty</td>
<td style="text-align: right;">-0.050979</td>
<td style="text-align: right;">0.055593</td>
<td style="text-align: right;">-0.916999</td>
<td style="text-align: left;">0.359144</td>
</tr>
<tr class="even">
<td style="text-align: left;">Income&lt; 400% poverty</td>
<td style="text-align: right;">-0.150961</td>
<td style="text-align: right;">0.056160</td>
<td style="text-align: right;">-2.688042</td>
<td style="text-align: left;">0.007188</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Income138-400% poverty</td>
<td style="text-align: right;">-0.222511</td>
<td style="text-align: right;">0.056902</td>
<td style="text-align: right;">-3.910396</td>
<td style="text-align: left;">0.000092</td>
</tr>
<tr class="even">
<td style="text-align: left;">IncomeAll</td>
<td style="text-align: right;">-0.321742</td>
<td style="text-align: right;">0.058373</td>
<td style="text-align: right;">-5.511799</td>
<td style="text-align: left;">&lt;0.000001</td>
</tr>
<tr class="odd">
<td style="text-align: left;">PCTIC</td>
<td style="text-align: right;">0.044709</td>
<td style="text-align: right;">0.002505</td>
<td style="text-align: right;">17.846588</td>
<td style="text-align: left;">&lt;0.000001</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="key-findings-from-model-output" class="level2">
<h2 class="anchored" data-anchor-id="key-findings-from-model-output">Key Findings From Model Output</h2>
<ul>
<li><p>Race was a strong predictor of disease prevalence. All race categories had large negative coefficients relative to the reference category. For instance, identifying as Asian (RaceASN) was associated with an average 13.99-point lower prevalence rate (p &lt; 0.000001 - way below the 0.05 threshold), and identifying as Black (RaceBLK) corresponded to a 7.60-point lower rate.</p></li>
<li><p>Sex was a statistically significant but modest predictor of disease prevalence. Compared to the reference category, identifying as female was associated with a 0.09-point lower average prevalence rate (p = 0.0226), while identifying as male corresponded to a 0.10-point higher rate (p = 0.0121). Although these effects were statistically significant, the magnitude of the differences was relatively small compared to other predictors such as race.</p></li>
<li><p>Income showed a negative relationship with disease prevalence, consistent with prior expectations. While the differences for low-income groups (&lt;200%, &lt;250% poverty) were not significant, the more inclusive groups (e.g., All, &lt;400%, 138–400%) showed statistically significant decreases in prevalence, with p-values &lt; 0.000001.</p></li>
<li><p>PCTIC (Percent Insured) was a highly significant and positive predictor, with a coefficient of 0.045 (p &lt; 0.000001). This finding supports the idea that areas with higher insurance coverage also report higher disease prevalence—likely due to better detection, screening, and diagnosis rates, rather than higher true incidence.</p></li>
</ul>
</section>
<section id="cross-validation-results" class="level2">
<h2 class="anchored" data-anchor-id="cross-validation-results">Cross-Validation Results</h2>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Cross-Validated Results</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">intercept</th>
<th style="text-align: right;">RMSE</th>
<th style="text-align: right;">Rsquared</th>
<th style="text-align: right;">MAE</th>
<th style="text-align: right;">RMSESD</th>
<th style="text-align: right;">RsquaredSD</th>
<th style="text-align: right;">MAESD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">TRUE</td>
<td style="text-align: right;">9.705001</td>
<td style="text-align: right;">0.141008</td>
<td style="text-align: right;">7.873173</td>
<td style="text-align: right;">0.01345</td>
<td style="text-align: right;">0.001351</td>
<td style="text-align: right;">0.014494</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We then performed 5-fold cross-validation using the caret package to assess the model’s generalizability (Table: Cross-Validated Results). The root mean squared error (RMSE) was 9.71, and the mean absolute error (MAE) was 7.87, suggesting moderate prediction error across folds. The cross-validated R-squared value of 0.14 indicates that the model explains about 14% of the variation in disease prevalence—a modest but meaningful amount given the complexity of health outcomes and the diversity of diseases included. While the model has limitations in predictive power, it does capture statistically and substantively meaningful patterns related to race, income, and insurance access.</p>
</section>
<section id="residual-analysis-and-model-assumptions" class="level2">
<h2 class="anchored" data-anchor-id="residual-analysis-and-model-assumptions">Residual Analysis and Model Assumptions</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="analysis_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A QQ plot of the standardized residuals shows that:</p>
<ul>
<li><p>Most residuals lie near the diagonal line, indicating approximate normality in the center of the distribution.</p></li>
<li><p>The tails deviate upward and downward, suggesting positive kurtosis (heavier tails than a normal distribution).</p></li>
</ul>
<p>This indicates the presence of extreme values or outliers and possible violations of the normality assumption. While this doesn’t invalidate the model, it may affect the reliability of p-values and confidence intervals. In future iterations, we might consider more robust regression techniques to reduce sensitivity to these outliers.</p>
</section>
</section>
<section id="flaws-and-limitations-in-analysis" class="level1">
<h1>Flaws and limitations in analysis</h1>
<p><strong>No causality</strong> – The analysis is based on cross-sectional observational data, which can reveal associations but not establish cause-and-effect relationships between variables.</p>
<p><strong>Simplified model</strong> - The linear regression model assumes linear relationships and does not account for potential interactions or non-linear effects. Key predictors such as education level, employment status, or geographic access to healthcare are not included and may confound the observed relationships.</p>
<p><strong>Small sample sizes</strong> – Some racial and income subgroups (e.g., Native Hawaiian/Pacific Islander or specific income brackets) have relatively small sample sizes, which may reduce statistical reliability and generalizability for those groups.</p>
<p><strong>Data merging challenges</strong> – Merging datasets with differing structures, time frames, or levels of geographic granularity may introduce inconsistencies or measurement errors. For instance, state-level averages may obscure important within-state variation or neighborhood-level disparities.</p>
<p><strong>Unmeasured factors</strong> – Factors such as language barriers, immigration status, healthcare provider bias, or local public health infrastructure were not captured in the datasets but may significantly affect both insurance access and chronic disease outcomes.</p>
<p><strong>Aggregation bias</strong> – Because our analyses are conducted at the state and subgroup levels, they may mask local nuances and individual-level variation. This can lead to aggregation bias, where trends observed in the data do not necessarily reflect the experiences of individuals within those groups.</p>
</section>
<section id="conclusions" class="level1">
<h1>Conclusions</h1>
<ol type="1">
<li><p><strong>Racial and Ethnic Disparities in Chronic Disease Prevalence:</strong> Our analysis confirms that chronic disease prevalence in the U.S. is unevenly distributed across racial and ethnic groups. Multiracial and American Indian/Alaska Native populations experience the highest average rates of multiple chronic conditions, while Asian populations consistently report the lowest. These disparities highlight the role of structural inequities, including differences in environmental exposures, healthcare access, and broader social determinants of health.</p></li>
<li><p><strong>Preventive Health Measure Usage and Its Impact:</strong> There are substantial disparities in the usage of preventive health services such as influenza vaccinations, cancer screenings, and physical activity counseling. Groups with lower utilization—particularly Hispanic, Black, and American Indian/Alaska Native populations—also tended to report higher disease burdens. This pattern reinforces the importance of equitable access to preventive care as a means of reducing chronic disease disparities.</p></li>
<li><p>**Socioeconomic Determinants of Health Disparities:&amp;&amp; Insurance coverage and income level emerged as critical factors shaping health outcomes. While higher income was generally associated with better insurance coverage, significant racial disparities in insurance access persisted even within the same income brackets. These findings point to systemic barriers—beyond just income—that prevent certain groups from obtaining adequate healthcare access.</p></li>
</ol>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/sussmanbu\.github\.io\/ma4615-sp25-final-project-team-7\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>