---
title: "Jess_DataMerge"
draft: TRUE
---
Libraries:
```{r}
library(tidyverse)
library(readr)
```



SAHIE Dataset
```{r}
# Done on local machine - won't work in project directory so commeneted steps here

# sahie_data <- read_csv("sahie_2022.csv", skip = 84)
# head(sahie_data)
```

Selecting Columns:
```{r}
# sahie_clean <- sahie_data %>%
  # Keep only state-level estimates (county_name is NA)
  # filter(is.na(county_name)) %>%
  
  # Select and rename relevant columns
  # select(
    # Year = "year",
    # Age = "agecat",
    # Race = "racecat",
    # Sex = "sexcat",
    # Income = "iprcat",
    # NIPR,
    # NUI,
    # NIC,
    # PCTUI,
    # PCTIC,
    # LocationDesc = "state_name"
  # ) %>%
  
  # mutate(Age = case_when(
    # Age == 0 ~ "< 65",
    # Age == 1 ~ "18-64",
    # Age == 2 ~ "40-64",
    # Age == 3 ~ "50-64",
    # Age == 4 ~ "< 18",
    # Age == 5 ~ "21-64",
    # TRUE ~ NA_character_
  # )) |>
  
  # Recode race/ethnicity values
  # mutate(Race = case_when(
    # Race == 0 ~ "OVR",   # All races
    # Race == 1 ~ "WHT",   # White alone, not Hispanic or Latino
    # Race == 2 ~ "BLK",   # Black or African American alone
    # Race == 3 ~ "HIS",   # Hispanic or Latino (any race)
    # Race == 4 ~ "AIAN",  # American Indian and Alaska Native alone
    # Race == 5 ~ "ASN",   # Asian alone
    # Race == 6 ~ "HAPI",  # Native Hawaiian and Other Pacific Islander alone
    # Race == 7 ~ "MRC",   # Two or More Races
    # TRUE ~ NA_character_           # Catch any unexpected values
  # )) |>
  
  # mutate(Sex = case_when(
    # Sex == 0 ~ "Both",
    # Sex == 1 ~ "Male",
    # Sex == 2 ~ "Female",
    # TRUE ~ NA_character_
  # )) |>
  
  # mutate(Income = case_when(
    # Income == 0 ~ "All",
    # Income == 1 ~ "< 200% poverty",
    # Income == 2 ~ "< 250% poverty",
    # Income == 3 ~ "< 135% poverty",
    # Income == 4 ~ "< 400% poverty",
    # Income == 5 ~ "138-400% poverty",
    # TRUE ~ NA_character_
  # ))

# head(sahie_clean)
```


```{r}
# saveRDS(sahie_clean, "sahie_cleaned.rds")
```

```{r}
# Load the RDS data set
sahie_cleaned <- readRDS(here::here("dataset", "sahie_cleaned.rds"))
head(sahie_cleaned)
```

Load in CDI Data
```{r}
cdi_cleaned <- readRDS(here::here("dataset", "dataclean.rds"))
cdi_cleaned <- cdi_cleaned %>%
  rename(Year = "YearStart")

head(cdi_cleaned)
```

Cleaning CDI a little more:
```{r}
cdi_race <- cdi_cleaned %>%
  filter(StratificationCategory1 == "Race/Ethnicity") %>%
  mutate(Race = case_when(
    StratificationID1 == "OVR" ~ "OVR",
    StratificationID1 == "WHT" ~ "WHT",
    StratificationID1 == "BLK" ~ "BLK",
    StratificationID1 == "HIS" ~ "HIS",
    StratificationID1 == "AIAN" ~ "AIAN",
    StratificationID1 == "ASN" ~ "ASN",
    StratificationID1 == "HAPI" ~ "HAPI",
    StratificationID1 == "API" ~ "HAPI",
    StratificationID1 == "MRC" ~ "MRC",
    TRUE ~ NA_character_
  )) |>
  select(-StratificationID1, -StratificationCategory1)
  

cdi_race
```

```{r}
cdi_2022 = cdi_race |>
  filter(Year == 2022) |>
  filter(!(LocationDesc %in% c("Virgin Islands", "Puerto Rico", "Guam", "United States")))

cdi_2022
```

MERGE:
```{r}
merged_data <- cdi_2022 %>%
  left_join(sahie_cleaned, by = c("Year", "LocationDesc", "Race"))

merged_data
```

```{r}
 # saveRDS(merged_data, "merged_data_2022.rds")
```

^ 
THIS DATA CAN BE LOADED IN USING THE COMMAND:
merged_data <- readRDS(here::here("dataset", "merged_data_2022.rds"))

