---
title: "Zihao"
format: html
draft: True
---

## Do chronic disease rates differ by gender and age group?

```{r}
data <- readRDS(here::here("dataset", "dataclean.rds"))
```

```{r}
library(dplyr)
library(ggplot2)
```

```{r}
demo_data <- data %>%
  filter(DataValueType == "Crude Prevalence")

gender_data <- demo_data %>% filter(StratificationCategory1 == "Sex")
age_data <- demo_data %>% filter(StratificationCategory1 == "Age")


# Gender
gender_asthma <- gender_data %>%
  filter(Topic == "Asthma") %>%
  group_by(StratificationID1) %>%
  summarise(avg_prevalence = mean(DataValue, na.rm = TRUE))

# Age
age_asthma <- age_data %>%
  filter(Topic == "Asthma") %>%
  group_by(StratificationID1) %>%
  summarise(avg_prevalence = mean(DataValue, na.rm = TRUE))

library(ggplot2)


#graph
ggplot(gender_asthma, aes(x = StratificationID1, y = avg_prevalence, fill = StratificationID1)) +
  geom_bar(stat = "identity") +
  labs(title = "Asthma Prevalence by Gender", x = "Gender", y = "Prevalence (%)") +
  theme_minimal()

ggplot(age_asthma, aes(x = StratificationID1, y = avg_prevalence, fill = StratificationID1)) +
  geom_bar(stat = "identity") +
  labs(title = "Asthma Prevalence by Age Group", x = "Age Group", y = "Prevalence (%)") +
  theme_minimal()

```


```{r}
library(tidyverse)
library(sf)         # for shapefiles (spatial data)
library(ggplot2)    # for plotting
library(dplyr)
library(here)
data <- readRDS(here("dataset", "dataclean.rds"))
```

```{r}
# Filter for actual  values
data_count <- data %>%
  filter(DataValueType == "Number")
```

```{r}
# Group and summarize by state
disease_counts <- data_count %>%
  mutate(region = tolower(LocationDesc)) %>%
  group_by(region) %>%
  summarise(total_cases_thousands = sum(DataValue, na.rm = TRUE) / 1000)
```

```{r}
# Load map
us_states <- map_data("state")
map_data <- left_join(us_states, disease_counts, by = "region")
```

```{r}
# Plot
ggplot(map_data, aes(x = long, y = lat, group = group, fill = total_cases_thousands)) +
  geom_polygon(color = "white") +
  scale_fill_gradient(
  low = "#e5f5e0", high = "#238b45", na.value = "grey90",
  labels = scales::label_number(suffix = "K")
) +
  theme_void() +
  labs(title = "Total Reported Disease Cases by State (in Thousands)", 
       fill = "Cases (K)")
```