---
title: "Blog Post 1"
description:  |
  Our team's first blog post, where we review potential dataset candidates.
author: "Team 7"
date: "2025-02-28"
draft: FALSE
---

# Dataset 1: [U.S. Chronic Disease Indicators (CDI)](https://data.cdc.gov/Chronic-Disease-Indicators/U-S-Chronic-Disease-Indicators/hksd-2xuw/about_data)

The CDI dataset was published by the Centers for Disease Control and Prevention (CDC) and developed through a consensus process involving the CDC, the Council of State and Territorial Epidemiologists, and the National Association of Chronic Disease Directors. The data is collected to support public health surveillance, policy development, and program planning at state and national levels. This comprehensive dataset consists of 309,215 rows and 34 columns, and includes 115 indicators spanning various health topics such as cancer, diabetes, cardiovascular disease, respiratory conditions, and social determinants of health.

After downloading the csv file for the data, we can load it into R using read.csv(). Potential cleaning steps include managing multiple stratification variables (the dataset includes StratificationCategory1, StratificationCategory2, etc.), addressing missing values, converting location identifiers to meaningful geographic variables, and creating derived variables for time-based analysis (the data includes YearStart and YearEnd, which have years spanning 2015-2022). Some of the main questions we hope to address are how racial disparities in disease prevalence and management vary across different states/regions, how racial disparities in chronic disease indicators have changed over time, and whether or not racial disparities in preventive health measures (like cancer screenings, vaccinations) correlate with disparities in disease outcomes. A few anticipated challenges include handling the volume of data, addressing any high-variance estimates (i.e. some racial/ethnic groups may have limited data in certain geographic areas), and effectively visualizing disparities across multiple dimensions (race, geography, time).

# Dataset 2: [Mental Health Client-Level Data (MH-CLD)](https://www.samhsa.gov/data/data-we-collect/mh-cld-mental-health-client-level-data/datafiles)

Published by the Substance Abuse and Mental Health Services Administration (SAMHSA), the MH-CLD is designed to compile demographic and mental health characteristics for clients who have received mental health services in facilities that report to state administrative data systems. Each state’s Mental Health Agency collects data on individuals who receive mental health services during a defined 12-month reporting period; this dataset contains information from the year 2022, consisting of 6,957,919 rows and 40 columns. The data was originally collected to support national mental health reporting and to inform policy decisions by providing insights into service usage across various demographics.

We can first load the data into RStudio by downloading the delimited data file and using read.csv(). We can then clean the dataset by handling missing values (e.g., dealing with the 14.3% missing responses for race), filtering records for relevance to our study, and rewriting categorical variables for clearer analysis. Some of the main questions we hope to address are what the most common disorders among different race groups are, how mental health outcomes differ based on race/ethnicity following service utilization, and what the racial disparities in mental health service are across different demographic groups. A few challenges we may face during our project include scaling down the data, and making sure to consider that different states may have varied definitions or categorizations of diagnoses and service types, affecting comparability.

# Dataset 3: [National Statistics by Parent Income Percentile, Gender, and Race](https://www.census.gov/programs-surveys/ces/data/public-use-data/race-and-economic-opportunity-data-tables.html)

This data derives from a larger study aimed at understanding the impact of parent income on children’s outcomes. The dataset was constructed using information from the U.S. Census Bureau and the American Community Survey (ACS). Confidentiality was prioritized, with data being cleared through the Census Bureau's Disclosure Review Board to protect individual identities. The data consists of 100 rows and 69 columns, and it covers children born between 1978 and 1983, focusing on various socio-economic indicators related to race and gender.

We can load the data into RStudio using read.csv(), and cleaning the data will involve handling missing values, ensuring numerical data are in the correct format for analysis, and removing any bins with suppressed data (as they won’t provide meaningful insights). Some of the main questions we hope to address are how racial disparities manifest in various child outcomes (education, employment, incarceration) based on parent income percentiles, how the mean child income rank differs based on parental homeownership/family structure, and what differences exist between children of different races and genders in terms of college attendance and marriage rates. Looking at the dataset, a few challenges we may face during our project include cleaning/better organizing the data, establishing statistically significant results in racial subgroups with smaller sample sizes, and interpreting correlation vs. causation between variables.
